import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

type OutputFile = Readonly<{ path: string; relativePath: string }>;

const repositoryRoot =
  process.env.REVO_SCRIPTS_BUILD_DIGEST_ROOT ?? fileURLToPath(new URL('..', import.meta.url));
const generatedDirectory = join(repositoryRoot, 'src/runtime/generated');
const generatedDigestPath = join(generatedDirectory, 'build-digest.ts');
const generatedImplementationPath = join(generatedDirectory, 'built-in-implementation.ts');

const builtInDefinitionEntries = [
  ['script:approval/subject', 'scripts/approval/subject/script.js'],
  ['script:git/commit', 'scripts/git/commit/script.js'],
  ['script:git/push', 'scripts/git/push/script.js'],
  ['script:git/status', 'scripts/git/status/script.js'],
  ['script:github/pull-request/mark-ready', 'scripts/github/pull-request/mark-ready/script.js'],
  ['script:github/pull-request/merge', 'scripts/github/pull-request/merge/script.js'],
  ['script:github/pull-request/readiness', 'scripts/github/pull-request/readiness/script.js'],
  ['script:github/pull-request/upsert', 'scripts/github/pull-request/upsert/script.js'],
  ['script:github/review-threads/resolve', 'scripts/github/review-thread/resolve/script.js'],
  ['script:github/review-threads/respond', 'scripts/github/review-thread/respond/script.js'],
] as const;

const collectJavaScriptFiles = async (directory: string): Promise<readonly string[]> => {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry): Promise<readonly string[]> => {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) {
        return collectJavaScriptFiles(path);
      }
      return entry.isFile() && path.endsWith('.js') ? [path] : [];
    }),
  );
  return nested.flat();
};

const outputFiles = async (directory: string): Promise<readonly OutputFile[]> =>
  (await collectJavaScriptFiles(directory))
    .map((path) => ({ path, relativePath: relative(directory, path).split(sep).join('/') }))
    .filter(({ relativePath }) => !relativePath.startsWith('runtime/generated/'))
    .sort((left, right) => left.relativePath.localeCompare(right.relativePath));

const importedRelativePaths = (source: string): readonly string[] =>
  [...source.matchAll(/\b(?:import|export)\s+(?:[^'";]*?\s+from\s+)?['"](\.[^'"]+)['"]/g)].map(
    (match) => {
      const importedPath = match[1];
      if (importedPath === undefined) {
        throw new Error('Expected a relative import path.');
      }
      return importedPath;
    },
  );

const digestForDefinition = async (
  entryPath: string,
  filesByPath: ReadonlyMap<string, OutputFile>,
): Promise<string> => {
  const closure = new Map<string, OutputFile>();
  const visit = async (relativePath: string): Promise<void> => {
    if (closure.has(relativePath)) {
      return;
    }
    const file = filesByPath.get(relativePath);
    if (file === undefined) {
      throw new Error(`Built-in definition closure is missing ${relativePath}.`);
    }
    closure.set(relativePath, file);
    const source = await readFile(file.path, 'utf8');
    await Promise.all(
      importedRelativePaths(source).map(async (importedPath) => {
        const resolvedPath = relative(sep, resolve(sep, dirname(relativePath), importedPath));
        if (filesByPath.has(resolvedPath)) {
          await visit(resolvedPath);
        }
      }),
    );
  };

  await visit(entryPath);
  const digest = createHash('sha256');
  const files = [...closure.values()].sort((left, right) =>
    left.relativePath.localeCompare(right.relativePath),
  );
  const contents = await Promise.all(
    files.map(async (file) => ({ file, bytes: await readFile(file.path) })),
  );
  for (const { file, bytes } of contents) {
    digest.update(file.relativePath, 'utf8');
    digest.update('\0');
    digest.update(String(bytes.byteLength), 'utf8');
    digest.update('\0');
    digest.update(bytes);
    digest.update('\0');
  }
  return `sha256:${digest.digest('hex')}`;
};

const buildDigestSource = (digests: ReadonlyMap<string, string>): string =>
  '// Generated by scripts/generate-build-digest.ts. Do not edit by hand.\n' +
  'export const builtInBuildDigests = {\n' +
  [...digests]
    .map(([scriptId, digest]) =>
      scriptId.length + 80 > 100
        ? `  '${scriptId}':\n    '${digest}',`
        : `  '${scriptId}': '${digest}',`,
    )
    .join('\n') +
  '\n} as const;\n';

const buildImplementationSource = (digests: ReadonlyMap<string, string>): string =>
  '// Generated by scripts/generate-build-digest.ts. Do not edit by hand.\n' +
  'export const builtInImplementation = (scriptId: string, version: string) => {\n' +
  '  switch (scriptId) {\n' +
  [...digests]
    .map(
      ([scriptId, digest]) =>
        `    case '${scriptId}': {\n` +
        '      return {\n' +
        `        id: 'revo.builtin.${scriptId.replace(/[:/]/g, '-')}',\n` +
        '        version,\n' +
        '        buildDigest:\n' +
        `          '${digest}' as const,\n` +
        '      };\n' +
        '    }',
    )
    .join('\n') +
  '\n    default: {\n' +
  '      throw new Error(`Unknown built-in script id: ${scriptId}`);\n' +
  '    }\n' +
  '  }\n' +
  '};\n';

const generate = async (): Promise<void> => {
  const temporaryOutput = await mkdtemp(join(tmpdir(), 'revo-scripts-build-'));
  try {
    execFileSync(
      'tsc',
      ['-p', 'tsconfig.build.json', '--outDir', temporaryOutput, '--sourceMap', 'false'],
      { cwd: repositoryRoot, stdio: 'inherit' },
    );
    const files = await outputFiles(temporaryOutput);
    const filesByPath = new Map(files.map((file) => [file.relativePath, file]));
    const digests = new Map(
      await Promise.all(
        builtInDefinitionEntries.map(
          async ([scriptId, entryPath]) =>
            [scriptId, await digestForDefinition(entryPath, filesByPath)] as const,
        ),
      ),
    );
    const digestSource = buildDigestSource(digests);
    const implementationSource = buildImplementationSource(digests);
    if (process.argv.includes('--check')) {
      if (
        (await readFile(generatedDigestPath, 'utf8')) !== digestSource ||
        (await readFile(generatedImplementationPath, 'utf8')) !== implementationSource
      ) {
        throw new Error('Generated build digest is stale. Run pnpm build:identity:generate.');
      }
      return;
    }
    await Promise.all([
      writeFile(generatedDigestPath, digestSource),
      writeFile(generatedImplementationPath, implementationSource),
    ]);
  } finally {
    await rm(temporaryOutput, { recursive: true, force: true });
  }
};

await generate();
