// Generated by scripts/generate-build-digest.ts. Do not edit by hand.
export const nodeGitProviderImplementationDigest =
  'sha256:5d0d76068e094c593f16600cd6d6345353f92d0d73f7fcf98fe5fb7e5cb2c649' as const;
