// Generated by scripts/generate-build-digest.ts. Do not edit by hand.
export const fetchGitHubProviderImplementationDigest =
  'sha256:faa7cad4a7dd68759deabed35e3ff93c7aad011c2ea27978d730e13e6428f373' as const;
